### ISSUE TITLE
Use explicit names

### ISSUE THREAD

**Issue by jecisc** [SamTheDev/Morphic-Widgets-FastTable#3]
Please, do not use unexplicit names like "ds" in EditingProvider. It's a sign of code smell in smalltalk and at the end we will lose less time to write "dataSource" than to ask ourself "what is ds" in some months.

**Comment by SamTh3D3v** [comment]
makes senses, i will fix that

**Comment by jecisc** [comment]
Also there is some unused variables in some classes, but I put this in the "not yet finished" category :)

**Comment by SamTh3D3v** [comment]
Indeed, that's why no PR was sent  to the main repo yet ;)), i am on it tho
